### PR TITLE
Created com.hutattedonmyarm.quote.md

### PR DESCRIPTION
**Pull request by hutattedonmyarm**

### CODE REVIEW

**Comment by 33mhz** [comment]
Thanks! I wonder if the pos+len should be optional and the quote source Not be, instead. It would be a lot easier for clients to minimally support this by user marking it:
User: "this is a quote"
Client: "what's the source of the quote?"
Go!
Versus requiring a minimum of:
U: "This is a quote"
C: "what is?"
U: "this here"

I guess to me, the most valuable part of it is the attribution, not the visual display. What do you think?

**Comment by hutattedonmyarm** [comment]
Hm I hadn't thought of it. I created that for the visual display and made the source optional to allow for "fun quotes", but considering you'd (probably?) never want to just put something in quotation marks without providing at least *some* form of attribution I think you're right

**Comment by 33mhz** [comment]
I propose:
```json
{
  "source_text": "@bazbt3",
  "source_url": "",
  "source_created_at": "",
  "pos": 3,
  "len": 12
}
```
field | | desc
--|--|--
source_text | required | description of who or what is being quoted. Clients can detect if it's a username starting with `@` or in combination with `source_url`.
source_url | | URL source of the quote
source_created_at | | Optional ISO 8601 time the quoted material was created
pos | | start position of the quote (usually only relevant if a whole block of text is the quote)
len | | (ditto `pos`)

Requiring that clients parse the quote in a specific format's restricting, I think. That is, if someone wants to say `I said "Here's a quarter", then Baz said, "That's so cool!"`, they might want to add some quote data, like source text and URL, which clients can easily display next to a post. Otherwise they can probably only display a quote in a different way if the quote is parsed a specific way and has the `raw`, and then still they'll have a lot of parsing to do, like taking quotation marks out, etc., depending how they're going to display the quote.

But I'm really advocating for a different use. Yours seems to be about displaying the existing text differently (highlighting it? What do you want clients to do?), and mine is more about adding data to the post that then tells clients "this is a quote, here's extra material", and can be listed, like "here's all the quotes made by this user."

**Comment by hutattedonmyarm** [comment]
Another idea: `pos` and `len` could be int-arrays to allow for split up quotes. Yes, I want to give clients the ability to display existing text differently (if they want). `source_pos` and `source_len` should be an (optional) part, just so that clients have the ability to format that part.
We could have `source_text` as the only required field to make sure we have some form of attribution,  add the `source_pos` and `source_len`  fields optionally, and change `pos` and `len` into arrays. This should IMHO cover both our use cases very well.

**Pull request merged**
