### PR TITLE
Adding the photo.tag raw type

### PR DESCRIPTION
**Pull request by objectivecosta**
Open to feedback :)

### CODE REVIEW

**Comment by 33mhz** [comment]
For reference, App.net did this: https://github.com/appdotnet/object-metadata/blob/master/annotations/net.app.core.phototag.md

I have a couple ideas right off the bat: use `user_id` instead of `username`, since usernames can change. Consider making positioning optional... Not sure how good or bad that is, but it seems like some may want to just go "this is a picture of User X" and not say "at 240x583".

**Comment by objectivecosta** [comment]
@33mhz Are +user objects supported in Pnut.io? If it were, we could embed the whole user object in the response! :)

EDIT:

Replaced usernames with user_ids, due to their mutability. Also changed the position to an object, since it is more readable that way!

**Comment by 33mhz** [comment]
Do you want to make this core `io.pnut.core.phototag` and use `"+io.pnut.core.user"` replacement values, embedding a user? If we're doing that, maybe there would be one `io.pnut.core.phototag` per user, not a list in each oembed. Maybe not.

An interesting paradigm: this is a post raw type? For attaching to posts, along with oembeds? Because it seems like you'd want this on the file instead, so that you don't have to tag photos every time you post a photo. In practice most photos are only attached to one post, but it's still natural to attach this as metadata for a file.

EDIT: Then you wouldn't have `ref` and `attached_to_type`. And maybe not `tags`, depending.

**Comment by objectivecosta** [comment]
@33mhz That makes much more sense! I didn't know files could have raw attached to them! Also, I didn't think about passing one per user. That looks much neater.

**Comment by 33mhz** [comment]
You're working against a non-existent spec here, of course... ;) Let's go with
```
"+io.pnut.core.user": {
  "user_id": "6",
  "format": "basic"
}
```

**Pull request closed without merging**
